public class SearchCriteriaExpansionTask {
    public static final String searchCriteriaExpansionTask = """
            Step 2: Expand the search criteria
            
            Broaden the scope of the search criteria by adding synonyms, related terms, variations, and descriptors or qualifiers to include related topics and relevant subtopics, using these methods:
            
            NOTE: Generate a comprehensive list of synonyms for the given word. This list is for internal reference only; select the most contextually appropriate synonyms (i.e., words found in the KJV Bible) from the list to include in the final response.
            
            Qualifiers (Keyword-based): Generate a comprehensive list of adjectives or descriptors that refine and provide context for the search term. Use these qualifiers to narrow or specify the scope of the search. For example, if the search term is 'sacrifice,' include 'living,' 'daily,' or 'personal' to provide more specific context.
            Lexical Semantic Relationships (Keyword-based): Lexical semantic relationships refer to the connections between words based on their meanings, such as synonyms, antonyms, hypernyms, and hyponyms. Use these relationships to expand the search criteria by including words with similar or contrasting meanings. For example, if the search term is 'hope,' expand it by including 'faith' (synonym) or 'fear' (antonym) to cover related aspects.
            Semantic Networks (Contextual-based): Generate a network of interconnected concepts that relate to the search term, including directly and indirectly related ideas. Use these connections to broaden the scope of the search. For example, if the search term is 'wisdom,' include 'knowledge,' 'understanding,' and 'prudence' to identify conceptually connected verses.
            Conceptual Similarity (Contextual-based): Generate a list of verses or terms that share similar underlying concepts or ideas with the search term. Use this list to broaden the search by identifying verses that are contextually similar. For example, if the term is 'faith,' include concepts like 'belief,' 'trust,' and 'hope.'
            Ontologies (Contextual-based): Generate a structured list of related terms and relationships using ontologies or structured knowledge bases. Use these terms to expand the search. For example, if the search term is 'sacrifice,' include related entities like 'offering,' 'altar,' and 'atonement.'
            Latent Semantic Analysis (LSA) (Contextual-based): Generate a list of words with hidden relationships to the search term using statistical analysis. Use these relationships to expand the search. For example, if the search term is 'covenant,' include terms like 'promise,' 'agreement,' and 'testament.'
            Latent Dirichlet Allocation (LDA) (Contextual-based): Generate a list of terms that share thematic similarity with the search term by applying topic modeling techniques. Use these terms to broaden the search. For example, if the term is 'salvation,' include 'redemption,' 'deliverance,' and 'atonement.'
            Lexical Expansion (Keyword-based): Generate a list of variations, synonyms, and related words for the search term. Use these terms to expand the search. For example, if the term is 'law,' include 'commandment,' 'statute,' and 'ordinance.'
            Taxonomies (Contextual-based): Generate a hierarchical list of classifications that relate to the search term. Use these classifications to explore related concepts and broaden the search. For example, if the term is 'angel,' include 'seraphim,' 'cherubim,' and 'archangel.'
            Topic Modeling (Contextual-based): Generate a list of verses grouped by themes or topics that are similar to the search term. Use these groupings to improve match accuracy. For example, if the term is 'love,' group related verses under themes like 'brotherly love,' 'divine love,' and 'sacrificial love.'
            Fuzzy Matching (Keyword-based): Generate a list of terms that are close in spelling or pronunciation to the search term. Use these similar terms to broaden the search. For example, if the search term is 'mercy,' include 'merry,' 'mercies,' and 'marcy.'
            Fuzzy Logic (Keyword-based): Generate a list of verses that partially match the search criteria using fuzzy logic techniques. Use these partial matches to broaden the search. For example, if the term is 'justice,' include verses related to 'judgment,' 'equity,' and 'fairness.'
            Subconcept (Contextual-based): Generate a list of more specific ideas that fall under the search term. Use these subconcepts to refine the search. For example, if the search term is 'fruit,' include specific ideas like 'grapes,' 'figs,' and 'olives.'
            Superconcept (Contextual-based): Generate a list of more general ideas that encompass the search term. Use these superconcepts to broaden the search. For example, if the term is 'bread,' include 'food,' 'provision,' and 'nourishment.'
            Subset (Contextual-based): Generate a list of smaller, contained parts of the broader search term. Use these subsets to refine the search. For example, if the term is 'armor,' include 'helmet,' 'breastplate,' and 'shield.'
            Superset (Contextual-based): Generate a list of broader categories that contain the search term. Use these supersets to broaden the search. For example, if the term is 'sandal,' include 'footwear,' 'clothing,' and 'attire.'
            Subdomain (Contextual-based): Generate a list of specialized areas within the domain of the search term. Use these subdomains to refine the search. For example, if the term is 'faith,' include 'justifying faith,' 'sanctifying faith,' and 'saving faith.'
            Domain (Contextual-based): Generate a list of overall categories or fields that relate to the search term. Use these domains to broaden the search. For example, if the term is 'prophecy,' include 'divine revelation,' 'spiritual gifts,' and 'future events.'
            Instance (Contextual-based): Generate a list of specific examples that illustrate the broader search term. Use these instances to refine the search. For example, if the term is 'altar,' include 'altar of incense,' 'altar of burnt offering,' and 'altar of witness.'
            Class (Contextual-based): Generate a list of broader groups or categories that the search term belongs to. Use these classes to broaden the search. For example, if the term is 'disciple,' include 'followers,' 'students,' and 'learners.'
            Contextual Hierarchies Using Hypernyms and Hyponyms (Contextual-based): Generate a list of broader (hypernyms) and more specific (hyponyms) terms related to the search term. Use these hierarchies to refine or broaden the search. For example, if the term is 'lamb,' include the hypernym 'animal' and hyponyms like 'sacrificial lamb' and 'paschal lamb.'
            
            """;
}